# Generated by Django 5.2.17 on 2026-09-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="título")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="identificador en la URL",
                    ),
                ),
                (
                    "bajada",
                    models.TextField(
                        blank=True,
                        help_text="Texto que aparece bajo el título.",
                        verbose_name="bajada",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Menor número, aparece antes.",
                        verbose_name="orden",
                    ),
                ),
                (
                    "publicada",
                    models.BooleanField(default=True, verbose_name="visible en la web"),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "página",
                "verbose_name_plural": "páginas",
                "ordering": ["orden", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="EnlacePagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="descripción"
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        blank=True,
                        help_text="Encabezado opcional. Los enlaces que comparten grupo se muestran juntos.",
                        max_length=120,
                        verbose_name="grupo",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="enlace externo")),
                (
                    "archivo",
                    models.FileField(
                        blank=True, upload_to="documentos/", verbose_name="documento"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="orden")),
                ("activo", models.BooleanField(default=True, verbose_name="visible")),
                (
                    "pagina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enlaces",
                        to="contenido.pagina",
                        verbose_name="página",
                    ),
                ),
            ],
            options={
                "verbose_name": "enlace",
                "verbose_name_plural": "enlaces",
                "ordering": ["orden", "id"],
            },
        ),
    ]
