# Generated by Django 5.2.17 on 2026-09-16 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enlacepagina",
            name="archivo",
            field=models.FileField(
                blank=True,
                help_text="Sólo se aceptan archivos PDF: la web los rotula así.",
                upload_to="documentos/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="documento",
            ),
        ),
    ]
