# Generated by Django 5.2.17 on 2026-09-15 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="identificador en la URL",
                    ),
                ),
                (
                    "resumen",
                    models.TextField(
                        blank=True,
                        help_text="Bajada que aparece bajo el título.",
                        verbose_name="resumen",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Menor número, aparece antes.",
                        verbose_name="orden",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(default=True, verbose_name="visible en la web"),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionSitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        default="CETACER", max_length=120, verbose_name="nombre"
                    ),
                ),
                (
                    "aniversario",
                    models.CharField(
                        blank=True,
                        default="60",
                        help_text="Se muestra en azul junto al nombre en el encabezado.",
                        max_length=10,
                        verbose_name="número de aniversario",
                    ),
                ),
                (
                    "descripcion_larga",
                    models.CharField(
                        default="CÁMARA EMPRESARIA DEL TRANSPORTE AUTOMOTOR DE CARGAS DE ENTRE RÍOS",
                        max_length=200,
                        verbose_name="razón social",
                    ),
                ),
                (
                    "cintillo",
                    models.CharField(
                        default="TRANSPORTE · FORMACIÓN · ENTRE RÍOS",
                        max_length=120,
                        verbose_name="texto del cintillo superior",
                    ),
                ),
                (
                    "titulo_hero",
                    models.CharField(
                        default="El próximo paso",
                        max_length=120,
                        verbose_name="título principal",
                    ),
                ),
                (
                    "titulo_hero_destacado",
                    models.CharField(
                        default="en tu camino.",
                        max_length=120,
                        verbose_name="continuación destacada del título",
                    ),
                ),
                (
                    "bajada_hero",
                    models.TextField(
                        default="Representamos a las empresas de transporte de cargas de la provincia. Gestioná la solicitud de turnos y consultá la grilla de fechas disponibles en un solo lugar.",
                        verbose_name="bajada del título",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        default="5493434695896",
                        help_text="Sin signos ni espacios. Ej: 5493434695896",
                        max_length=30,
                        verbose_name="WhatsApp (formato internacional)",
                    ),
                ),
                (
                    "whatsapp_visible",
                    models.CharField(
                        default="343 469-5896",
                        max_length=40,
                        verbose_name="WhatsApp como se muestra",
                    ),
                ),
                (
                    "telefonos",
                    models.CharField(
                        default="(0343) 4330742 · 4332621 · 4332622",
                        max_length=200,
                        verbose_name="teléfonos",
                    ),
                ),
                (
                    "telefono_principal",
                    models.CharField(
                        default="(0343) 4330742",
                        max_length=40,
                        verbose_name="teléfono del cintillo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="administracion@cetacer.com",
                        max_length=254,
                        verbose_name="correo",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        default="Almirante Brown 2185, Paraná, Entre Ríos",
                        max_length=200,
                        verbose_name="dirección",
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        default="Paraná, Entre Ríos",
                        max_length=100,
                        verbose_name="ciudad",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        default="https://facebook.com/cetacer",
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "url_boleta",
                    models.URLField(
                        blank=True,
                        default="https://sicapro.com.ar/solicitudonline.aspx",
                        verbose_name="URL de la boleta de pago",
                    ),
                ),
                (
                    "inscripcion_online",
                    models.BooleanField(
                        default=True,
                        help_text="Si está apagado, la web sólo ofrece el turno por WhatsApp.",
                        verbose_name="habilitar preinscripción online",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración del sitio",
                "verbose_name_plural": "configuración del sitio",
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="identificador en la URL",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dejar vacío si el precio se informa por WhatsApp.",
                        max_digits=12,
                        null=True,
                        verbose_name="precio",
                    ),
                ),
                (
                    "precio_a_consultar",
                    models.BooleanField(
                        default=False,
                        verbose_name="mostrar «Consultar» en lugar del precio",
                    ),
                ),
                (
                    "duracion_horario",
                    models.CharField(
                        default="A confirmar al asignar turno",
                        max_length=200,
                        verbose_name="duración y horario",
                    ),
                ),
                (
                    "cupo_sugerido",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Cupo que se propone al crear una comisión nueva.",
                        verbose_name="cupo sugerido",
                    ),
                ),
                (
                    "cupo_texto",
                    models.CharField(
                        default="Cupo limitado",
                        help_text="Se usa si el curso no tiene comisiones publicadas.",
                        max_length=100,
                        verbose_name="texto del cupo en la web",
                    ),
                ),
                ("requisitos", models.TextField(blank=True, verbose_name="requisitos")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción ampliada"),
                ),
                (
                    "link_externo",
                    models.URLField(
                        blank=True, verbose_name="enlace a más información"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="visible en la web"),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="orden dentro de la categoría"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cursos",
                        to="cursos.categoria",
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "curso",
                "verbose_name_plural": "cursos",
                "ordering": ["categoria__orden", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Sólo si el curso dura más de un día.",
                        null=True,
                        verbose_name="fecha de finalización",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(
                        blank=True, null=True, verbose_name="hora de inicio"
                    ),
                ),
                (
                    "hora_fin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="hora de finalización"
                    ),
                ),
                ("cupo", models.PositiveIntegerField(default=25, verbose_name="cupo")),
                (
                    "lugar",
                    models.CharField(
                        blank=True,
                        help_text="Si se deja vacío se usa la sede de la configuración del sitio.",
                        max_length=200,
                        verbose_name="lugar",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicada", "Publicada"),
                            ("en_curso", "En curso"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones internas"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comisiones_a_cargo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="instructor a cargo",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones",
                        to="cursos.curso",
                        verbose_name="curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "comisión",
                "verbose_name_plural": "comisiones",
                "ordering": ["fecha_inicio", "hora_inicio"],
                "indexes": [
                    models.Index(
                        fields=["fecha_inicio", "estado"],
                        name="cursos_comi_fecha_i_7b8102_idx",
                    )
                ],
            },
        ),
    ]
