# Generated by Django 5.2.17 on 2026-09-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="link_externo",
        ),
        migrations.AddField(
            model_name="configuracionsitio",
            name="pago_aclaracion",
            field=models.TextField(
                blank=True,
                default="Enviá el comprobante por WhatsApp junto con la foto del DNI y de la licencia de conducir, frente y dorso.",
                verbose_name="aclaración sobre el pago",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsitio",
            name="pago_alias",
            field=models.CharField(
                blank=True,
                default="FPT.LICENCIAPROF",
                max_length=60,
                verbose_name="alias para transferencias",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsitio",
            name="pago_banco",
            field=models.CharField(
                blank=True, default="Banco Nación", max_length=80, verbose_name="banco"
            ),
        ),
        migrations.AddField(
            model_name="configuracionsitio",
            name="pago_titular",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="titular de la cuenta"
            ),
        ),
    ]
