# Generated by Django 5.2.17 on 2026-09-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0004_separar_renovacion_y_ampliacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracionsitio",
            name="inscripcion_online",
        ),
        migrations.RemoveField(
            model_name="configuracionsitio",
            name="url_boleta",
        ),
    ]
