# Generated by Django 5.2.17 on 2026-09-28 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0005_sacar_reserva_online_y_boleta"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="icono",
            field=models.FileField(
                blank=True,
                help_text="Se muestra junto al título de la categoría en la web. Preferentemente SVG; también sirve PNG o WebP de 64×64.",
                upload_to="iconos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["svg", "png", "webp"]
                    )
                ],
                verbose_name="icono",
            ),
        ),
    ]
