# Generated by Django 5.2.17 on 2026-09-28 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0006_icono_de_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenPortada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.FileField(
                        help_text="Apaisada y de al menos 1600 px de ancho: se recorta a lo alto.",
                        upload_to="portada/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                        verbose_name="imagen",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Para uso interno: ayuda a distinguirlas en esta lista.",
                        max_length=120,
                        verbose_name="de qué es la foto",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "activa",
                    models.BooleanField(default=True, verbose_name="visible en la web"),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes_portada",
                        to="cursos.configuracionsitio",
                        verbose_name="sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen de portada",
                "verbose_name_plural": "imágenes de portada",
                "ordering": ["orden", "id"],
            },
        ),
    ]
