# Generated by Django 5.2.17 on 2026-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0007_imagenes_de_portada"),
    ]

    operations = [
        migrations.AddField(
            model_name="comision",
            name="cerrada",
            field=models.BooleanField(
                default=False,
                help_text="La web la muestra completa y no se inscribe a nadie más, sin tocar el cupo.",
                verbose_name="marcar como completa",
            ),
        ),
    ]
