# Generated by Django 5.2.17 on 2026-09-15 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="razón social"
                    ),
                ),
                (
                    "cuit",
                    models.CharField(blank=True, max_length=20, verbose_name="CUIT"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo"
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="localidad"
                    ),
                ),
                (
                    "socia",
                    models.BooleanField(
                        default=False,
                        help_text="Se usa para separar el listado de asociadas en los informes.",
                        verbose_name="empresa asociada a CETACER",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{6,12}$", "Ingresá el DNI sin puntos ni espacios."
                            )
                        ],
                        verbose_name="DNI",
                    ),
                ),
                ("apellido", models.CharField(max_length=120, verbose_name="apellido")),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo"
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="localidad"
                    ),
                ),
                (
                    "categoria_licencia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: C, D.2, E.1",
                        max_length=40,
                        verbose_name="categoría de licencia",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participantes",
                        to="inscripciones.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "participante",
                "verbose_name_plural": "participantes",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("preinscripta", "Preinscripto"),
                            ("confirmada", "Confirmado"),
                            ("asistio", "Asistió"),
                            ("ausente", "Ausente"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="preinscripta",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "pago",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagado", "Pagado"),
                            ("exento", "Exento"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="pago",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="monto abonado",
                    ),
                ),
                (
                    "comprobante",
                    models.CharField(
                        blank=True,
                        help_text="Número de boleta e-SICAPRO o recibo interno.",
                        max_length=100,
                        verbose_name="comprobante",
                    ),
                ),
                (
                    "psicofisico_vigente",
                    models.BooleanField(
                        default=False, verbose_name="psicofísico vigente"
                    ),
                ),
                (
                    "documentacion_completa",
                    models.BooleanField(
                        default=False, verbose_name="documentación completa"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("panel", "Carga interna"),
                            ("web", "Formulario web"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="panel",
                        max_length=20,
                        verbose_name="origen",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de inscripción"
                    ),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "comision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="cursos.comision",
                        verbose_name="comisión",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscripciones_cargadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargada por",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="inscripciones.participante",
                        verbose_name="participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscripción",
                "verbose_name_plural": "inscripciones",
                "ordering": ["participante__apellido", "participante__nombre"],
            },
        ),
        migrations.AddIndex(
            model_name="participante",
            index=models.Index(
                fields=["apellido", "nombre"], name="inscripcion_apellid_358aef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inscripcion",
            index=models.Index(
                fields=["estado", "pago"], name="inscripcion_estado_ea3535_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inscripcion",
            constraint=models.UniqueConstraint(
                fields=("comision", "participante"),
                name="participante_unico_por_comision",
            ),
        ),
    ]
